---
label: Project
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: projectType
  type: select
  default: []
  config:
    required: false
    options:
    - MDRV
    - Client
    - Personal
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Project Type
- name: client
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: clients
      file: content/clients/cosmiccompositions.md
      path: 
  label: Client
  showOnly:
    field: projectType
    value: Client
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
- name: projectColor
  type: color
  label: Project Color
  config:
    required: false
    color_format: Hex
  default: "#000000"
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Description
- name: year
  type: number
  label: Year
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: tags
  type: tag_list
  default: []
  label: Tags
- name: projectURL
  type: text
  config:
    required: false
  label: Project URL
- name: projectURLSite
  type: text
  config:
    required: false
  label: Project URL Site
pages:
- content/posts/chromegan.md
- content/posts/die-tur-die-wichtigkeit-des-banalen.md
- content/posts/dj-gran-sport-memphis-house.md
- content/posts/eos-chamber-orchestra.md
- content/posts/glaskasten-marl.md
- content/posts/good-die-my-friend.md
- content/posts/pl-agv3.md
- content/posts/sag-meister.md
- content/posts/spektrum-werkschau.md
- content/posts/youtube-intro.md
