---
label: Project
hide_body: true
fields:
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
- name: title
  type: text
  config:
    required: false
  label: Title
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: year
  type: number
  label: Year
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: tags
  type: tag_list
  default: []
  label: Tags
pages:
- content/posts/spektrum-werkschau.md
